### PR TITLE
Close FDs and add scale tests

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by jonludlam** [comment]
It looks like we're not unmapping the files ever. I think we need to fix this before merging.

**Comment by johnelse** [comment]
I assumed the munmap happened when the bigarray was garbage collected - there doesn't seem to be an explicit unmap call in the bigarray API. I'll investigate...

**Comment by johnelse** [comment]
Running a `Gc.major` unmaps the file at either end once the reader/writer has gone out of scope.

**Comment by jonludlam** [comment]
Awesome. OK, in which case, I think we can go ahead and merge.

**Pull request merged**
