### PR TITLE
Close FDs and add scale tests

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Don't merge, just seeing what travis thinks :)

**Comment by euanh** [comment]
@johnelse: Should we move this to a feature branch, since there is lots of fallout to deal with before it can be merged?

**Comment by euanh** [comment]
This pull request is blocked until we fix the packages which use it.   Please reopen when that happens.

**Comment by johnelse** [comment]
Reopened as #28

**Pull request closed without merging**
